### PR TITLE
Added force delete option to PurgeCommand for soft delete compatibility

### PR DESCRIPTION
**Pull request by zmorris**
Hi I ran into an issue when I tried the purge command, because the project I'm working on uses soft deletes. This PR adds a `--force` option to call `forceDelete()` internally, falling back to the regular `delete()` otherwise:

```
php artisan expirable:purge --force
```

Feel free to modify this however you want, it's just for your convenience! And many thanks for making this package.

***

Also just FYI, hard deleting rows will fail most of the time in the real world on tables with foreign keys that don't have the cascade-deletes option set. So ideally this would delete the child tables first. So for example if `users.phone_id` pointed to `phones.id`, then the users row should be deleted before the phones row. Otherwise users.phone_id has nothing to point to. This is beyond the scope of your command though, and should probably be provided by a third party framework or built into Laravel. A workaround is to pass the models in child-to-parent order:

```
php artisan expirable:purge --force "App\User" "App\Phone"
```

Or list them that way in the `purge` key in `config/expirable.php`:

```
    'purge' => [
        App\User::class,
        App\Phone::class,
    ],
```

### CODE REVIEW

**Comment by zmorris** [comment]
Hi I ran into an issue when I tried the purge command, because the project I'm working on uses soft deletes. This PR adds a `--force` option to call `forceDelete()` internally, falling back to the regular `delete()` otherwise:

```
php artisan expirable:purge --force
```

Feel free to modify this however you want, it's just for your convenience! And many thanks for making this package.

***

Also just FYI, hard deleting rows will fail most of the time in the real world on tables with foreign keys that don't have the cascade-deletes option set. So ideally this would delete the child tables first. So for example if `users.phone_id` pointed to `phones.id`, then the phones row should be deleted before the users row. This is beyond the scope of your command though, and should probably be provided by a third party framework or built into Laravel. A workaround is to pass the models in child-to-parent order:

```
php artisan expirable:purge --force 'App\Phone' 'App\User'
```

Or list them that way in the `purge` key in `config/expirable.php`:

```
    'purge' => [
        App\Phone::class,
        App\User::class,
    ],
```

**Comment by alajusticia** [comment]
Hi, thank you for your contribution!

By the time I created this command, the need was to completely delete records from the database.
This purge command was created to meet this need, as an action that would be performed after any "archiving" action such as the soft deletion and expiration of a model. We run it as a CRON job, to perform a massive deletion of data no longer required and to free up space. Thus, it performs a force delete to ensure that all records are deleted, even with the models that use soft deletions.

For me the expiration and the soft deletion are on the same level (which I see as "archiving"). If a model is expired, it will behave like if it was soft deleted and will, by default, no longer be retrieved in database queries. Therefore, in my use case, I see the point of soft deleting a model that is not already expired, but I don't see the point of soft deleting an expired model, it feels redundant. If the data is required to be present in our database for integrity, I will not use the purge command on this model and let it just be expired.

Can you tell me a little more about your use case?

Also, I'm concerned because this would introduce a breaking change, by inverting the default behavior of the command.

You're right about foreign keys, and as you said it's beyond the scope of this command, but I could update the README file to point this limitation.

**Comment by zmorris** [comment]
Ah good points, ya I also wondered about backward compatibility. My use case is to call `php artisan expirable:purge` in a cron job running Laravel's schedule, to delete/archive rows after they've expired. The idea is to avoid database triggers, although they would be the most formal solution IMHO. I really wish that databases had column views, so that I could declaratively make one column a function of another, similarly to how table views work. Come to think of it, I may actually need to set an `expired` boolean column instead, after the expiration date passes.

I went ahead and changed `--force` to `--mode=hard/soft`, falling back to the "mode" key in config/expirable.php and defaulting to "hard". That way it will continue to use forceDelete() unless the user opts in to delete() by setting `"mode" => "soft"` or calling `php artisan expirable:purge --mode=soft`

I struggled with this for a bit, because `--option=` commands are prone to accidental mistyping in the real world. For example, `--soft=` might get misconstrued as `--soft` by itself:

```
# --soft eats the next word, like --soft="App\User" (causing no models to be specified)
php artisan expirable:purge --soft "App\User"

# --mode is unlikely to be left by itself (so the model gets specified correctly)
php artisan expirable:purge --mode=soft "App\User"
```

I think it's clever how you used `--since=`, because a preposition isn't likely to get left by itself accidentally. I found several other candidates like `via` and `as`, as well as nouns like `method`. But you might want to override `method` someday if the user wanted to call a different function like `->archive()`. That's how I settled on `mode`.

If you decide to use this PR, feel free to just cherry-pick the final result if you want a clean commit history. I'm not concerned about attribution.

Edit: dangit I messed up the whitespace in the config. All the more reason to just copy this into your own commit :-)

**Comment by alajusticia** [comment]
Thanks, yes indeed I prefer the mode option as it offers backward compatibility :)

**Pull request merged**
